// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr7QSsuhpP-ANjgiF_6pHOcu_f8s-jPRc',
    appId: '1:469449748154:web:36bcedea225e1d2edf1c83',
    messagingSenderId: '469449748154',
    projectId: 'travelplanner-7f5f0',
    authDomain: 'travelplanner-7f5f0.firebaseapp.com',
    storageBucket: 'travelplanner-7f5f0.appspot.com',
    measurementId: 'G-W47K3PJD3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7U3Fb6MG0IgwVrphlmETjs9HX5UsliBQ',
    appId: '1:469449748154:android:905d7f05c633107bdf1c83',
    messagingSenderId: '469449748154',
    projectId: 'travelplanner-7f5f0',
    storageBucket: 'travelplanner-7f5f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUdEyDDUJAj3mZBJMeph8WYxZpLXY_d-g',
    appId: '1:469449748154:ios:3b9135f4947bb8d3df1c83',
    messagingSenderId: '469449748154',
    projectId: 'travelplanner-7f5f0',
    storageBucket: 'travelplanner-7f5f0.appspot.com',
    iosClientId: '469449748154-er3ejsonrq887hh2kdqjmq60bmqso6f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelPlanner',
  );
}
